### ISSUE TITLE
python-catkin-pkg and python3-catkin-pkg cannot both be installed side-by-side

### ISSUE THREAD

**Issue by jack-oquin** [ros-infrastructure/catkin_pkg#125]
The root problem seems to be the fact that both packages install scripts in `/usr/bin` with the same names, like `catkin_create_package` and `catkin_tag_changelog`.

This is clearly contrary to the Debian and Ubuntu intention to support both Python dialects side by side. I did some poking around to see how they recommend doing it. I didn't find any good documentation on that, so I experimented with the .deb releases of `python-sphinx` and `python3-sphinx`.

Those packages _can_ be installed side-by-side. Each version installs its scripts in different directories:
- /usr/share/sphinx/scripts/python
- /usr/share/sphinx/scripts/python3

Then, they symlink one or the other set of scripts into `/usr/bin`. So far, I don't see how that was done.

On my Trusty system, the `python` versions are selected. I don't know if that is because Python 2 is the default version, or because I installed `python-sphinx` first. I don't see anything in `/etc/alternatives` or `/var/lib/dpkg/alternatives`.

Surely, there is a reasonable solution to this packaging problem.

**Comment by dirk-thomas** [comment]
This is indeed the common way to package Debian packages.

We use https://github.com/astraw/stdeb to package ROS Python packages and https://github.com/ros-infrastructure/ros_release_python to automate the process. Afaik stdeb does not support this at the moment. So we would either need to come up with a completely different approach to create the Debian packages or extend stdeb with that feature.

It is not likely that we will work on either of these two options in the near future. If anybody known an easier way to achieve this or want to work on this feature we would be very happy to support that effort.

**Comment by jack-oquin** [comment]
It looks like the recommended Debian approach uses the ``debian/links`` mechanism:

* https://wiki.debian.org/Python/Packaging#Example_2:_Python_application

**Comment by de-vri-es** [comment]
One approach I used for a similar problem when packaging software for Arch Linux was to split the package in a library and a scripts/tools package. Then the library packages can be installed side by side, and the scripts/tools package conflict and provide the same target (might be the name of one of the two packages).

This method only allows one of the scripts/tools package to be installed, but they should behave identical so that should not be a problem.

You would have the following packages:
* `python-catkin-pkg` (library)
* `python2-catkin-pkg` (library)
* `python-catkin-pkg-scripts` (conflicts with `python-catkin-pkg-scripts`)
* `python2-catkin-pkg-scripts` (conflicts with and provides `python-catkin-pkg-scripts`)

The `*-scripts` packages depend on the matching library package.

In Arch Linux, packages conflicting with themselves is perfectly fine. It's a common technique to have alternative implementations of the same thing in different packages where only one implementation can be installed.

Not sure if this approach would be easier to combine with `stdeb` and `ros_release_python`.

**Comment by dirk-thomas** [comment]
Splitting the package into the library part and the command line tools is indeed common. But I see a few downsides for the described approach:

* One "problem" with the described splitting and banking is that all tutorials as well as all packages reference `python-catkin-pkg` as a dependency. So if the packages are split this way all tutorials need to be changed as well as several package dependencies need to be updated. That sounds like quite an effort and breakage to me.

* And since these Python packages affect all ROS distros that would also imply the EOL ROS distros like e.g. Hydro can't be updated to the new dependency names and will suddenly stop working (since the lack the scripts).

* Also if this "splitting" isn't automated by the release process it would imply that every Python packages is split into two which increases the maintenance overhead.

**Comment by de-vri-es** [comment]
One solution to the backwards compatibility problem could be to keep the current name for the scripts/tools package and name the other one `python[23]?-catkin-pkglib` or something along those lines.

Increased maintenance overhead remains a concern.

**Comment by dirk-thomas** [comment]
We will finally address this issue. The goals are:
* Be able to import the Python modules in both Python and Python 3.
* One set of scripts is being installed on the path. It is not relevant which Python version the scripts use. For the user / caller that is transparent / an implementation detail.
* Keep the release process (currently using `ros_release_python`) as simple as possible.

The following requirements need to be met in order to not break backward compatibility (existing installations as well as instructions):
* Installing `python-catkin-pkg` or `python3-catkin-pkg`, in both cases
  * `catkin_*` scripts on the path
  * Python modules importable in the specific Python version

Based on the requirements and goals there is one direct conclusion:
* The scripts and the Python modules must be separated into different Debian packages since the Python modules need to be installable for Python 2 as well as Python 3 but only one set of scripts can be installed.

The following is the proposal to move forward:
* The scripts stay in the Debian packages with the current names.
  * Those *are still not* side-by-side installable.
* The Python modules are being moved into new Debian packages (e.g. `python-catkin-pkg-modules` and `python3-catkin-pkg-modules`).
  * Those *are* now side-by-side installable.
* The existing Debian packages depend on their corresponding `-modules` package
* (-) Having another repo / package.
* (+) Keeps the release process simple.

Alternative Approach:
* The Python modules stay in the current Debian package
* New single Debian package containing the scripts.
* Those need to be shell scripts (for all supported platforms) trying each Python version.
* (-) Would require more effort.

The next steps:
* Split this repo into two repos (one for the scripts, one for the modules).
* The new repo will be named `catkin_pkg_modules` and will only contain the modules.
* The existing repo will depend on the package in the new repo and will only contain the scripts.
* Both are being released with `ros_release_python`.

**Comment by jack-oquin** [comment]
Is there some technical reason preventing the release of multiple packages from a single repo?

**Comment by dirk-thomas** [comment]
While ROS packages require all packages in a repo to have the same version for the release process this is not the case for these Python packages. So, no, there is no technical reason that requires separate repos.

`catkin_pkg` and `catkin_pkg_modules` could be kept in the same repo in subfolders. Each subfolder would have its own `stdeb.cfg` file. When tagging a version the package name would need to be prepended to the version number in order to ensure the tag is unique.

I like that idea to resolve the con of the proposed approach.

**Comment by dirk-thomas** [comment]
I have to revise my conclusion after thinking a bit more about the consequences:

One drawback of moving the content into subfolder might be that it would break use cases where users clone this repo and install the package by executing the `setup.py` file (since it is not in the root anymore). It is also a common use case to pass the git url to `pip`. That being said it might be "safer" to split the content into two repos.

**Comment by de-vri-es** [comment]
A single repo does have the advantage that development is easier. Keeping changes between library and scripts in sync will be much easier.

**Comment by dirk-thomas** [comment]
I have though long about the overhead of splitting the packages "in source". Also if you install via PIP you shouldn't need more than one package. And since I don't like compromises I looked into how much effort and customization and alternative approach would take.

Please see #157 which relies on ros-infrastructure/ros_release_python#15. It only affects the generated Debian package. It now generates two Debian packages with the names proposed above. While it requires some effort in the `setup.py` of the package the customization is transparent and the PIP release is unchanged (a single package).

This will need some thorough testing and comparing with existing packages. It should be easy to apply the same to other Python package if necessary.

**Comment by de-vri-es** [comment]
Can't PIP deal with dependencies itself? Not that I think there is anything wrong with keeping a single package for PIP and splitting for debian. I do worry a bit that this is specific to debian/ubuntu. What about other supported platforms?

**Comment by dirk-thomas** [comment]
Imo the problem itself is specific to the packaging process. We don't automate that process for anything but Debian packages. Usually the maintainer takes care of splitting packages manually (e.g. `-dev` and `non-dev` packages).

We could do the same splitting for PIP. It is just not necessary and if you look at other packages available through PIP we would probably be the only one doing that.

**Comment by de-vri-es** [comment]
I agree that it is a packaging problem, though it might be an additional hurdle to automate packaging for other platforms in the future. But I suppose that's an issue that can be tackled at that time. It makes little sense to try to solve the problem for any number of unknown platforms right now.

In conclusion: I think its a good approach.

**Comment by jack-oquin** [comment]
:+1: looks good to me

**Comment by dirk-thomas** [comment]
I will wait with a new release of `python-catkin-pkg` until after the weekend. That way I am around if it goes south...

**Comment by dirk-thomas** [comment]
Version 0.3.0 has been released using #157 which makes the packages `python-catkin-pkg-modules` and `python3-catkin-pkg-modules` side-by-side installable (see http://wiki.ros.org/action/diff/catkin_pkg/Installation?action=diff&rev1=2&rev2=3).

See https://github.com/ros-infrastructure/catkin_pkg/pull/157#issuecomment-279593635 for a "problem" with the update process.
