### ISSUE TITLE
find_package() for catkin_ws/devil and catkin_ws/src

### ISSUE THREAD

**Issue by Baycken** [ros-infrastructure/catkin_pkg#187]
If `find_package` from `packages` was run from the top level of a catkin workspace, it will find both the devel and src of a package in the workspace. Will it be possible to add a check for the pair to eliminate the error originate from the devel/src pair?

**Comment by dirk-thomas** [comment]
The description doesn't contain enough information to provide you with feedback. Can you please describe what you want to do and why you want to do it.

It sounds like you are pointing the search path to the root of a workspace rather than to the `src` or `devel` folder. That should never be necessary and is likely not supported.

**Comment by Baycken** [comment]
OK, we are setting the $ROS_PACKAGE_PATH to the root of a workspace, and this cause `rosdep` to freak out. Once $ROS_PACKAGE_PATH is set to `src` only of the workspace, very thing works fine.

Thanks for the quick reply!
