### ISSUE TITLE
Regression/Error: "Only one <build_type> element is permitted".

### ISSUE THREAD

**Issue by facontidavide** [ros-infrastructure/catkin_pkg#336]
I think this was introduced in version 0.5.0

This doesn't work anymore:
```xml
  <export>
      <build_type condition="$ROS_VERSION == 2">ament_cmake</build_type>
      <build_type condition="$ROS_VERSION == 1">catkin</build_type>
  </export>
```
If I run `echo $ROS_VERSION` I can see either 1 or 2

Error message:

```
Repository type: git
Found packages: behaviortree_cpp_v3
Traceback (most recent call last):
  File "/usr/bin/catkin_prepare_release", line 33, in <module>
    sys.exit(load_entry_point('catkin-pkg==0.5.0', 'console_scripts', 'catkin_prepare_release')())
  File "/usr/lib/python3/dist-packages/catkin_pkg/cli/prepare_release.py", line 217, in main
    _main()
  File "/usr/lib/python3/dist-packages/catkin_pkg/cli/prepare_release.py", line 272, in _main
    build_type = package.get_build_type()
  File "/usr/lib/python3/dist-packages/catkin_pkg/package.py", line 167, in get_build_type
    raise InvalidPackage('Only one <build_type> element is permitted.', self.filename)
catkin_pkg.package.InvalidPackage: Error(s) in package '././package.xml':
Only one <build_type> element is permitted.

```

**Comment by cottsay** [comment]
Probably related to #331 (@wjwwood FYI).

I can take a closer look on Monday.

**Comment by wjwwood** [comment]
Yes, I think it was exposed by that pr but all we did was use the existing method for extracting the build type rather than manually extracting it. But we didn't change the method that accesses the build type. 

So I guess the official api considers that invalid or maybe it needs to be invoked differently. I'll have to look into more to know what is the right. 

At a higher level how should the tool proceed if in one situation it's a support build type but in another it is not supported? Does consider both build type tags? Should the user be required to set the ROS version (in this case) as an ebb car before invoking the tool?

**Comment by nuclearsandwich** [comment]
> So I guess the official api considers that invalid or maybe it needs to be invoked differently. I'll have to look into more to know what is the right.

The [`Package.get_build_type()` function](https://github.com/ros-infrastructure/catkin_pkg/blob/master/src/catkin_pkg/package.py#L150-L167) implicitly expects that either there is exactly one unconditional build type or that package conditions are evaluated before getting the build type.

The version check scripts don't otherwise necessitate an active ROS context as far as I know.

I can see a few possible ways to resolve this:

* Circumvent the accessor function and check all exported build types

* Evaluate package conditions using environment context (if there is one) or a fallback context

* Catch the error and require the version bump to be run in an environment context.


It occurs to me that we could "just not support" multiple build type packages.
This seems initially attractive if you assume that ROS 1's star is fading but I think that it will be some time before it goes out completely and it implies that we don't expect to deal with any future build system transitions. While none are currently anticipated ROS transitioned from rosbuild to catkin and it makes sense to at least consider the possibility that ROS 2 may require a transition in the future.

At the moment, the only build type dependent behavior is for the ament_python build type. I've never seen a package with the build type
```xml
<export>
  <build_type condition="$ROS_VERSION == 2">ament_python</build_type>
  <build_type condition="$ROS_VERSION == 1">catkin</build_type>
</export>
```

But if there's one out there, it represents a case where the update functions would actually do different things depending on the context.

**Comment by facontidavide** [comment]
> At the moment, the only build type dependent behavior is for the ament_python build type. I've never seen a package with the build type
> ...
> But if there's one out there, it represents a case where the update functions would actually do different things depending on the context.

Well, ALL my packages (plotjuggler, behaviortree, etc) build like that and the DO different things. This new regression is blocking be from creating new releases.

> It occurs to me that we could "just not support" multiple build type packages.
That will be hugely annoying for me

**Comment by nuclearsandwich** [comment]
> That will be hugely annoying for me

The feedback is definitely heard and appreciated. I wanted to make it explicit that I don't consider  not supporting this case a viable option which I can't do if I don't mention it at all. My apologies if I gave the impression that it was under consideration.

> Well, ALL my packages (plotjuggler, behaviortree, etc) build like that and the DO different things.

I'm confused, aren't all your packages conditionally using `catkin` or `ament_cmake`? The case I described above is conditional between `catkin` and <code>ament_<em>python</em></code>.

**Comment by nuclearsandwich** [comment]
> * Circumvent the accessor function and check all exported build types

Spiked this out in https://github.com/ros-infrastructure/catkin_pkg/pull/337 just to see it work.

**Comment by nuclearsandwich** [comment]
> It looks like there may be two separate code paths for bumping versions and #331 only covered one.

This isn't correct. `catkin_pkg.package_version.update_versions()` is the only method for actually changing the version in files on disk but it checks for the presence of a setup.py file *before* checking the package build type and thus wasn't hitting problems unless the package had a setup.py.

**Comment by nuclearsandwich** [comment]
@facontidavide we've merged a couple of PRs which together address all known regressions when using `catkin_prepare_release` and `catkin_package_version` in packages which contain multiple, conditional build types.

I'm planning to release catkin_pkg 0.5.1 tomorrow which includes those fixes. If you have the opportunity and interest to temporarily install catkin_pkg from `master` and let us know whether all your issues are resolved that would be most welcome. Thanks again for reporting the issue!

**Comment by jlblancoc** [comment]
Hi!

I found exactly the same issue than @facontidavide while trying to release a package intended to support ROS1/ROS2 from one single branch, with: 

```
 <export>
    <build_type condition="$ROS_VERSION == 1">catkin</build_type>
    <build_type condition="$ROS_VERSION == 2">ament_cmake</build_type>
 </export>
```

Running with catkin-pkg=0.5.0 fails: 

```bash
$ catkin_prepare_release 
Prepare the source repository for a release.
Repository type: git
Found packages: mrpt_msgs
Traceback (most recent call last):
  File "/usr/local/bin/catkin_prepare_release", line 11, in <module>
    load_entry_point('catkin-pkg==0.5.0', 'console_scripts', 'catkin_prepare_release')()
  File "/usr/local/lib/python2.7/dist-packages/catkin_pkg-0.5.0-py2.7.egg/catkin_pkg/cli/prepare_release.py", line 217, in main
    _main()
  File "/usr/local/lib/python2.7/dist-packages/catkin_pkg-0.5.0-py2.7.egg/catkin_pkg/cli/prepare_release.py", line 272, in _main
    build_type = package.get_build_type()
  File "/usr/local/lib/python2.7/dist-packages/catkin_pkg-0.5.0-py2.7.egg/catkin_pkg/package.py", line 167, in get_build_type
    raise InvalidPackage('Only one <build_type> element is permitted.', self.filename)
catkin_pkg.package.InvalidPackage: Error(s) in package '././package.xml':
Only one <build_type> element is permitted.
```

while running v0.5.2 works, so I can confirm the new release solved this issue, thanks!!
